server.port=8082

spring.datasource.url=jdbc:postgresql://localhost/postgres
spring.datasource.username=postgres
spring.datasource.password=demo
spring.flyway.table=flyway_schema_history_user_service
